# This is a root makefile which builds all the prject.
# In this case it build 'app' and 'tests'.

# Main prorab include, should go first in every makefile.
include $(d)../../../src/prorab.mk

# NOTE: whitespaces around 'Makefile' is to test that those do not harm!
$(eval $(call prorab-include-subdirs,  Makefile ))
