= prorab reference

Minimum version of `GNU make` required is `3.81`.

Before using **prorab** one has to include it.

.example
[source,makefile]
....
include prorab.mk
....

== d

Prorab defines the `d` variable which represents the directory in which the `makefile` resides. Absolute path.
When one makefile includes another one using `prorab-include` or `prorab-try-include` macro the `d` variable is substituted accordingly for the included makefile while it is evaluated.

== prorab_root_dir

Prorab defines `prorab_root_dir` variable which represents the directory of the root makefile. The root makefile is the initial makefile evaluated when `make` is executed. For root makefile `d` is same as `prorab_root_dir`.

== os

Prorab defines the `os` variable which indicates the host system on which the `make` is executed.

.values
- `linux` - any linux system
- `macosx` - any Mac OS X system
- `windows` - Windows `Msys2` or `Cygwin` environment.

== prorab_nproc

Prorab defines the `prorab_nproc` variable which indicates number of physical CPUs on the system (number of physical threads).

== prorab_blank

Prorab defines blank variable which has empty value. This kind of variables are sometimes needed, for example for defining tab character.

== prorab_tab

Prorab defines a variable holding tab character.

== prorab_space

Prorab defines a variable holding space character.

== a

Prorab defines `a` variable which indicates one of two verbosity levels.

.values
- empty - high verbosity level
- `@` - low verbosity level

The value of `a` is affected by `verbose` input variable or by its shorthand version `v`. See `verbose` variable description for more info.

The `a` variable is to be used as a prefix for each recipe line which is supposed to have configurable verbosity level.

== verbose

Input variable which sets the verbosity level.

.values
- `true` - high verbosity level. This value results in `a` variable being set to empty value.
- `false` - low verbosity level. This value results in `a` variable being set to `@`.
- empty - set verbosity level according to `v` variable value. See below for more info about `v` variable.

.example
[source,sh]
....
$ make verbose=true
....

== v

Shorthand version of `verbose` input variable.

.values
- empty, `0`, `false` - same as `verbose` being set to `false`.
- any other value - same as `verbose` being set to `true`.

Note that priority of `v` variable is less than `verbose` variable. For example if `v=1` and `verbose=false` the resulting `a` will be set to `@`, i.e. low verbosity level.

.example
[source,sh]
....
$ make v=t
....

== autojobs

Input variable which controls the parallel execution. It allows setting number of parallel jobs to the number of physical CPU cores present on the system.

.values
- `true` - set number of parallel `make` jobs to number of CPU cores present on the system.
- `false` - do not change number of parallel jobs. It can be 1 by default or the value specified by user via `-j` command line argument of `make`.
- empty - set parallel jobs in accordance with value of `aj` variable. See below for more info about `aj` variable.

.example
[source,sh]
....
$ make autojobs=true
....

== aj

Shorthand for `autojobs` input variable.

.values
- empty, `0`, `false` - same as `autojobs` being set to `false`.
- any other value - same as `autojobs` being set to `true.

Note that priority of `aj` variable is less than `autojobs` variable. For example if `aj=1` and `autojobs=false` the number of parallel jobs will not be touched.

== .RECIPEPREFIX

By default in `GNU make` the prefix for recipe lines is the **tab** character. `GNU make` allows overriding the character by setting the `.RECIPEPREFIX` variable but the initial value of the `.RECIPEPREFIX` is empty, which results in using the default recipe prefix character, i.e. **tab** character.

Prorab explicitly sets the `.RECIPEPREFIX` to the actual **tab** character.

== PREFIX

In case `PREFIX` variable is empty, prorab sets it to `/usr/local`

== dot_so

Prorab sets the `dot_so` variable to the shared library files suffix which is native for the host system.

.values
- `.so` - for Linux
- `.dylib` - for Mac OS X
- `.dll` - for Windows

== dot_exe

Prorab sets the `dot_exe` variable to the executable files suffix which is native for the host system.

.values
- empty - for Linux and Mac OS X
- `.exe` - for Windows

== prorab-inlcude

Include another makefile adjusting the `d` variable for the included file. Include the given makefile only once. In case the given makefile has already been included before then nothing is done. In case specified makefile does not exist the evaluation fails.

.syntax
[source,makefile]
....
$(eval $(call prorab-include, <makefile>))
....

.arguments
- `makefile` - path to the makefile to include. Relative to `$(d)`.

.example
[source,makefile]
....
include prorab.mk

$(eval $(call prorab-include, ../some_dir/makefile))
....

== prorab-try-include

Same as `prorab-include` but does not fail in case the specified makefile does not exist.

== prorab-include-subdirs

Include makefiles from all subdirectories of `$(d)`. Subdirectories which do not have a makefile are ignored.

.syntax
[source,makefile]
....
$(eval $(prorab-include-subdirs))
$(eval $(call prorab-include-subdirs, <makefile-name>))
....

.arguments
- `makefile-name` - name of the makefile to search for.

Note: `$(eval $(prorab-include-subdirs))` is same as `$(eval $(call prorab-include-subdirs, makefile))`

.example
[source,makefile]
....

include prorab.mk

$(eval $(call prorab-include-subdirs, Makefile))
....

== prorab-clear-this-vars

Clear all variables which have `this_` prefix.

Some variables, instead of clearing, are set to their default values.

.variables set to default values:
- `this_dot_cxx`
- `this_dot_hxx`
- `this_cc`
- `this_cxx`
- `this_ar`
- `this_as`
- `this_as_supports_deps_gen`
- `this_ld`
- `this_cppflags`
- `this_cflags`
- `this_cxxflags`
- `this_asflags`
- `this_ldflags`
- `this_ldlibs`

.syntax
[source,makefile]
....
$(eval $(prorab-clear-this-vars))
....

Note, that `prorab.mk` already have a call to this macro at its end. So, right after including `prorab.mk` one can be sure that all `this_`-prefixed variables are empty or set to their default values.

.example
[source,makefile]
....
inlcude prorab.mk

this_some_var := hello world

$(info this_some_var before = $(this_some_var)

$(eval $(prorab-clear-this-vars))

$(info this_some_var after = $(this_some_var))
....

== prorab-rwildcard

Recursively search the given directory for all files matching pattern.

.syntax
[source,makefile]
....
$(call prorab-rwildcard, <dir>, <pattern>)
....

.arguments
 - `dir` - root directory to search, relative to `$(d)`.
 - `pattern` - pattern to match files, can be several patterns separated by space.

.example
[source,makefile]
....
include prorab.mk

this_as_srcs := $(call prorab-rwildcard, src/asm, *.asm *.S)
....

== prorab-src-dir

Recursively find all source files. This is just a wrapper for `prorab-rwildcard` with pattern `*$(this_dot_cxx) *.c *.S`.

.syntax
[source,makefile]
....
$(call prorab-src-dir, <directory>)
....

.arguments
- `directory` - root directory to search for sources. Relative to `$(d)`.

.example
[source,makefile]
....
include prorab.mk

this_srcs := $(call prorab-src-dir, src/my_source_dir)
....

== prorab-hdr-dir

Recursively find all header files. This is just a wrapper for `prorab-rwildcard` with pattern `*$(this_dot_hxx) *.h`.

.syntax
[source,makefile]
....
$(call prorab-hdr-dir, <directory>)
....

.arguments
- `directory` - root directory to search for headers. Relative to `$(d)`.

.example
[source,makefile]
....
include prorab.mk

this_hdrs := $(call prorab-hdr-dir, src/include)
....

== prorab-config

Apply configuration from the given directory. The argument to the macro is the path to the directory which contains configuration files. The configuration file to take is specified by the `config` variable, or its shorthand alias `c`. The `config` variable has priority over `c`. If none of the `config` or `c` variables are set upon the `prorab.mk` inclusion the `config` variable is set to value `default`. Upon `prorab.mk` inclusion the `config` and `c` variable contents are synchronized, so that both variables have equal contents.

- First, the the macro sets the `config_dir` variable to an absolute path to the configurations directory.
- Then the macro sets the `this_out_dir` variable to `out/$(c)/` value.
- Then the macro includes the file `$(config).mk` from the configurations directory.
- The macro also defines `clean-all` target which cleans all configurations by removing the whole `out` directory.

.syntax
[source,makefile]
....
$(eval $(call prorab-config, <directory>))
....

.arguments
- `directory` - directory which contains configuration files. Relative to `$(d)`.

.example
[source,makefile]
....
###
### let our config files be in ../config directory relatively to our makefile directory
###


##########################
### ../config/base/base.mk 

# base settings for all configs
this_cxxflags += -Wall
this_cxxflags += -Werror


########################
### ../config/release.mk

# include common config for all other configurations
include $(config_dir)base/base.mk

# release configuration specific settings
this_cxxflags += -O3


############
### makefile

include prorab.mk

# include the configuration file
$(eval $(call prorab-config, ../config))

this_name := example_app

this_srcs := main.cpp

# our application specific settings
this_cxxflags += -g

$(eval $(prorab-build-app))
....

Usage from command line:
....
$ make config=release
....
or
....
$ make c=release
....

== prorab-config-default

Use specified configuration as the default configuration.

If none of the `config` or `c` variables are defined upon `prorab.mk` inclusion then both of those are set to value `default`. That means that `default.mk` configuration file is to be used by `prorab-config` macro. The `prorab-config-default` macro allows "redirecting" the default configuration to the specified configuration from within the `default.mk` configuration file.

.syntax
[source,makefile]
....
$(eval $(call prorab-config-default, <configuration-name>))
....

.arguments
- `configuration-name` - the configuration name to use as default configuration.

.example
[source,makefile]
....
##############
### default.mk

# make the 'release' configuration to be used by default
$(eval $(call prorab-config-default, release))
....

== prorab-build-app

Generate application build targets.

.syntax
[source,makefile]
....
this_name := <name>
this_srcs := <c-plusplus-as-sources>
this_c_srcs := <c-sources>
this_cxx_srcs := <plusplus-sources>
this_as_srcs := <assembler-sources>
this_cc := <c-compiler>
this_cxx := <cplusplus-compiler>
this_as := <assembler-compiler>
this_ld := <linker>
this_dot_cxx := <cplusplus-file-suffix>
this_cflags :=/+= <c-compiler-flags>
this_cxxflags :=/+= <cplusplus-compiler-flags>
this_asflags :=/+= <assembler-flags>
this_as_supports_deps_gen := <enable-assembler-deps-gen>
this_ldflags :=/+= <linker-flags>
this_ldlibs :=/+= <linker-libs>
this_cppflags :=/+= <preprocessor-flags>
this_out_dir := <out-directory>
this_no_install := <disable-install-targets>
this_hdrs := <c-cplusplus-header-files>
this_c_hdrs := <c-header-files>
this_cxx_hdrs := <cplusplus-header-files>
this_dot_hxx := <cplusplus-header-file-suffix>

$(eval $(prorab-build-app))
....

.arguments
- `this_name` - name of the application. It will be used to generate the output binary filename. **Mandatory**.
- `this_srcs` - list of sources, ok to use `+=` right a way. Relative to `$(d)`. Files with suffix `$(this_dot_cxx)` will be compiled by C++ compiler, files with suffix `.c` will be compiled with C compiler, files with suffix `.S` will be compiled with assembler.
- `this_c_srcs` - list of source files to be compiled by C compiler. Rleative to `$(d)`.
- `this_cxx_srcs` - list of source files to be compiled by C++ compiler. Relative to `$(d)`.
- `this_as_srcs` - list of sources files to be compiled by assembler. Relative to `$(d)`.
- `this_cc` - C compiler to use. Defaults to `$(CC)`.
- `this_cxx` - C++ compiler to use. Defaults to `$(CXX)`.
- `this_as` - assembler to use. Defaults to `$(AS)`.
- `this_ld` - linker to use. Defaults to `$(this_cc)`.
- `this_dot_cxx` - C++ source files suffix. Used to filter C++ source files from `$(this_srcs)`. Defaults to `.cpp`.
- `this_cflags` - C compiler flags. Defaults to `$(CFLAGS)`.
- `this_cxxflags` - C++ compiler flags. Defaults to `$(CXXFLAGS)`.
- `this_asflags` - assembler flags. Defaults to `$(ASFLAGS)`.
- `this_as_supports_deps_gen` - enable dependency files generation for assembler. Defaults to `true`.
- `this_ldflags` - linker flags. Defaults to `$(LDFLAGS)`.
- `this_ldlibs` - linker libraries. Defaults to `$(LDLIBS)`.
- `this_cppflags` - preprocessor flags. Defaults to `$(CPPFLAGS)`.
- `this_out_dir` - output directory. This is where all the build artefacts are to be stored. Relative to `$(d)`. Defaults to `./`.
- `this_no_install` - disable `install` targets. Can be `true` or `false`. Defaults to `false`.
- `this_hdrs` - list of header files to check compilation for (see explanation below). The files with suffix `$(this_dot_hxx)` will be compiled with C++ compiler, files with suffix `.h` will be compiled with C compiler. Rleative to `$(d)`.
- `this_c_hdrs` - list of C header files to check compilation for (see explanation below). Rleative to `$(d)`.
- `this_cxx_hdrs` - list of C++ header files to check compilation for (see explanation below). Rleative to `$(d)`.
- `this_dot_hxx` - C++ header files suffix. Used to filter C++ header files from `$(this_hdrs)`. Defaults to `.hpp`.

Note: `this_ldlibs` and `this_ldflags` are separated because sometimes order of linker flags, object files and libraries matters. So, linker flags go first, then go object files and then go linker libraries.

The `this_hdrs`, `this_cxx_hdrs` and `this_c_hdrs` specify the header files to check for compilation. For each header file a trivial C/C++ source file will be generated which includes the header file twice. Then those generated C++ files are compiled. This checks that the header file does not miss include guard and itself includes all the needed dependency header files. Compilation is done with the same compiler flags as the normal source files.

.output variables
- `prorab_this_name` - resulting name of the binary file (for example on Windows it will have .exe suffix appended). Absolute path.
- `prorab_this_objs` - list of generated object files. Absolute paths.
- `prorab_this_obj_dir` - object files output directory.
- `prorab_this_obj_spacer` - spacer for object files output. See details in generated object files target below.

.generated targets
- `$(prorab_this_name):` - link executable. This target is added to `all` target dependencies.
- `install::` - install the executable to the system. The executable binary is installed to `$(DESTDIR)$(PREFIX)/bin/`. The target is only generated if `$(this_no_install)` is `false`.
- `uninstall::` - remove the executable from the system. The executable is deleted from install path. The target is only generated if `$(this_no_install)` is `false`.
- `clean::` - remove build artifacts.
- `$(prorab_this_obj_dir)$(prorab_this_obj_spacer)%.o:` - compile source files to object files.

.example
[source,makefile]
....
include prorab.mk

this_name := myapp

this_cxxflags += -Wall
this_cxxflags += -DDEBUG
this_cxxflags += -I $(d)my_includes/some_dir
this_cflags += -Wall

this_ldlibs += -lpthread

this_srcs += main.cpp myapp.cpp legacy.c

$(eval $(prorab-build-app))
....

== prorab-build-lib

Generate library build targets.

.syntax
[source,makefile]
....
# library specific input variables
this_soname := <so-name>
this_headers_dir := <headers-dir>
this_headers_install_dir := <headers-install-dir>
this_install_hdrs := <headers-to-install>
this_install_c_hdrs := <c-headers-to-install>
this_install_cxx_hdrs := <cxx-headers-to-install>
this_static_lib_only := <static-lib-only>
this_ar := <archiver>

# same input variables as for application
this_name := <name>
this_srcs := <c-plusplus-as-sources>
this_c_srcs := <c-sources>
this_cxx_srcs := <plusplus-sources>
this_as_srcs := <assembler-sources>
this_cc := <c-compiler>
this_cxx := <cplusplus-compiler>
this_as := <assembler-compiler>
this_ld := <linker>
this_dot_cxx := <cplusplus-file-suffix>
this_cflags :=/+= <c-compiler-flags>
this_cxxflags :=/+= <cplusplus-compiler-flags>
this_asflags :=/+= <assembler-flags>
this_as_supports_deps_gen := <enable-assembler-deps-gen>
this_ldflags :=/+= <linker-flags>
this_ldlibs :=/+= <linker-libs>
this_cppflags :=/+= <preprocessor-flags>
this_out_dir := <out-directory>
this_no_install := <disable-install-targets>
this_hdrs := <c-cplusplus-header-files>
this_c_hdrs := <c-header-files>
this_cxx_hdrs := <cplusplus-header-files>
this_dot_hxx := <cplusplus-header-file-suffix>

$(eval $(prorab-build-lib))
....

.arguments
- `this_soname` - so name for dynamic library. **Mandatory**
- `this_headers_dir` - root directory of the header files which are to be installed with the library. Relative to `$(d)`.
- `this_headers_install_dir` - header files installation destination directory. Relative to `$(DESTDIR)$(PREFIX)/include`. Can be empty, then header files are installed straight to `$(DESTDIR)$(PREFIX)/include`.
- `this_install_hdrs` - list of header files to install. Relative to `$(d)`. If `this_install_hdrs`, `this_install_c_hdrs` and `this_install_cxx_hdrs` are empty, then the `this_headers_dir` directory is searched recursively for C (`.h`) and C++ header files (`$(this_dot_hxx)`). The `install` target will install these header files to `$(DESTDIR)$(PREFIX)/include/$(this_headers_install_dir)` preserving directory structure under `this_headers_dir` directory. Also, the `test` target will test these header files for compilation, same as headers from `this_hdrs`, but with no compilation flags, except `-std=...` filtered from `$(this_cflags)`/`$(this_cxxflags)`.
- `this_install_c_hdrs` - list of `c`-only header files to install. See `this_install_hdrs` for details. Relative to `$(d)`. The `test` target will test these header files for compilation.
- `this_install_cxx_hdrs` - list of `c++`-only header files to install. See `this_install_hdrs` for details. Relative to `$(d)`. The `test` target will test these header files for compilation.
- `this_static_lib_only` - disables building of shared library. If `true` only static library is built. Otherwise both, shared and static libraries are built. Defaults to empty.
- `this_ar` - the archiver program to use. Defaults to `$(AR)`.
- `this_name` - name of the library. It will be used to generate the output binary filename. **Mandatory**.
- `this_srcs` - list of sources, ok to use `+=` right a way. Relative to `$(d)`. Files with suffix `$(this_dot_cxx)` will be compiled by C++ compiler, files with suffix `.c` will be compiled with C compiler, files with suffix `.S` will be compiled with assembler.
- `this_c_srcs` - list of source files to be compiled by C compiler. Rleative to `$(d)`.
- `this_cxx_srcs` - list of source files to be compiled by C++ compiler. Relative to `$(d)`.
- `this_as_srcs` - list of sources files to be compiled by assembler. Relative to `$(d)`.
- `this_cc` - C compiler to use. Defaults to `$(CC)`.
- `this_cxx` - C++ compiler to use. Defaults to `$(CXX)`.
- `this_as` - assembler to use. Defaults to `$(AS)`.
- `this_ld` - linker to use. Defaults to `$(this_cc)`.
- `this_dot_cxx` - C++ source files suffix. Used to filter C++ source files from `$(this_srcs)`. Defaults to `.cpp`.
- `this_cflags` - C compiler flags. Defaults to `$(CFLAGS)`.
- `this_cxxflags` - C++ compiler flags. Defaults to `$(CXXFLAGS)`.
- `this_asflags` - assembler flags. Defaults to `$(ASFLAGS)`.
- `this_as_supports_deps_gen` - enable dependency files generation for assembler. Defaults to `true`.
- `this_ldflags` - linker flags. Defaults to `$(LDFLAGS)`.
- `this_ldlibs` - linker libraries. Defaults to `$(LDLIBS)`.
- `this_cppflags` - preprocessor flags. Defaults to `$(CPPFLAGS)`.
- `this_out_dir` - output directory. This is where all the build artefacts are to be stored. Relative to `$(d)`. Defaults to `./`.
- `this_no_install` - disable `install` targets. Can be `true` or `false`. Defaults to `false`.
- `this_hdrs` - list of header files to check compilation for (see explanation below). The files with suffix `$(this_dot_hxx)` will be compiled with C++ compiler, files with suffix `.h` will be compiled with C compiler. Rleative to `$(d)`.
- `this_c_hdrs` - list of C header files to check compilation for (see explanation below). Rleative to `$(d)`.
- `this_cxx_hdrs` - list of C++ header files to check compilation for (see explanation below). Rleative to `$(d)`.
- `this_dot_hxx` - C++ header files suffix. Used to filter C++ header files from `$(this_hdrs)`. Defaults to `.hpp`.

Note: `this_ldlibs` and `this_ldflags` are separated because sometimes order of linker flags, object files and libraries matters. So, linker flags go first, then go object files and then go linker libraries.

The `this_hdrs`, `this_cxx_hdrs` and `this_c_hdrs` specify the header files to check for compilation. For each header file a trivial C/C++ source file will be generated which includes the header file twice. Then those generated C++ files are compiled. This checks that the header file does not miss include guard and itself includes all the needed dependency header files. Compilation is done with the same compiler flags as the normal source files.

.output variables
- `prorab_this_name` - resulting name of the binary file. Absolute path.
- `prorab_this_symbolic_name` - resulting symbolic link to shared library. Absolute path.
- `prorab_this_static_lib` - resulting filename of the static library. Absolute path.
- `prorab_this_objs` - list of generated object files. Absolute paths.
- `prorab_this_obj_dir` - object files output directory.
- `prorab_this_obj_spacer` - spacer for object files output. See details in generated object files target below.

.generated targets
- `$(prorab_this_name):` - link the binary. This target is added to `all` target dependencies.
- `$(prorab_this_static_lib):` - create static library. This target is added to `all` target dependencies.
- `install::` - install the binary, its symbolic link and header files to the system. The binary is installed to `$(DESTDIR)$(PREFIX)/lib/`, header files are installed to `$(DESTDIR)$(PREFIX)/inlcude/`. The target is only generated if `$(this_no_install)` is `false`.
- `uninstall::` - remove the binary and header files from the system. The binary and header files are deleted from install path. The target is only generated if `$(this_no_install)` is `false`.
- `clean::` - remove build artifacts.
- `test::` - test installable header files for compilation.
- `$(prorab_this_obj_dir)$(prorab_this_obj_spacer)%.o:` - compile source files to object files.

.example
[source,makefile]
....
include prorab.mk

this_name := mylib

this_soname := 0

this_cxxflags += -Wall
this_cxxflags += -DDEBUG
this_cflags += -Wall
this_ldlibs += -lpthread

this_srcs += main.cpp myapp.cpp

$(eval $(prorab-build-lib))
....
