include $(d)../../../../src/prorab.mk

this_name := lib1

this_soname := 0

this_srcs := $(call prorab-src-dir, .)

this_out_dir := build

this_cxxflags += -fPIC

$(eval $(prorab-build-lib))

# $(prorab_this_name): $(abspath $(d)../lib2/build/liblib2$(dot_so))

# $(eval $(call prorab-include, ../lib2/makefile))
