include $(d)../../../../src/prorab2.mk

this_name := lib1

this_soname := 0

this_srcs := $(call prorab-src-dir, .)

this_out_dir := build

this_cxxflags += -fPIC

this_no_install := true

$(eval $(prorab-build-lib))
