include $(d)../../../../src/prorab2.mk

this_out_dir := out

this_name := stuff

this_soname := 0

this_srcs := $(call prorab-src-dir,.)

this_hdrs := $(call prorab-hdr-dir,.)

this_cxxflags += -fPIC

$(eval $(prorab-build-lib))
