#This is a root makefile which builds all the prject.
#In this case it build 'app' and 'tests'.

#Main prorab include, should go first in every makefile.
include prorab.mk


#This prorab macro includes all the makefiles it could find in subdirectories
$(eval $(prorab-include-subdirs))
