include $(d)prorab.mk


#install *.mk and *.sh
install::
	$(prorab_echo)install -d $(DESTDIR)$(PREFIX)/include
	$(prorab_echo)install $(d)prorab.mk $(DESTDIR)$(PREFIX)/include
	$(prorab_echo)install -d $(DESTDIR)$(PREFIX)/bin
	$(prorab_echo)install $(d)*.sh $(DESTDIR)$(PREFIX)/bin
