#This is a root makefile which builds all the prject.
#In this case it build 'app' and 'tests'.

#Main prorab include, should go first in every makefile.
include $(d)../../../src/prorab.mk


#This prorab macro includes all the makefiles it could find in subdirectories
$(eval $(prorab-build-subdirs))
