name: ci
on: [push, pull_request]
env:
  PACKAGE_NAME: ${{ github.event.repository.name }}
  MYCI_JFROG_USERNAME: ivan.gagis@gmail.com
  MYCI_JFROG_PASSWORD: ${{ secrets.MYCI_JFROG_PASSWORD }}
  MYCI_GIT_USERNAME: igagis
  MYCI_GIT_PASSWORD: ${{ secrets.MYCI_GIT_ACCESS_TOKEN }}
jobs:
##### linux #####
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: debian, codename: stretch, image_owner: , package_type: deb}
          - {os: debian, codename: buster, image_owner: , package_type: deb}
          - {os: ubuntu, codename: bionic, image_owner: , package_type: deb}
          - {os: ubuntu, codename: focal, image_owner: , package_type: deb}
          - {os: raspbian, codename: stretch, image_owner: igagis/, package_type: deb, labels: [arm,docker]}
          - {os: raspbian, codename: buster, image_owner: igagis/, package_type: deb, labels: [arm,docker]}
    runs-on: ${{ (matrix.labels == '' && 'ubuntu-latest') || matrix.labels }}
    container: ${{ matrix.image_owner }}${{ matrix.os }}:${{ matrix.codename }}
    name: linux - ${{ matrix.image_owner }}${{ matrix.os }}:${{ matrix.codename }}
    steps:
      - name: git clone
        uses: actions/checkout@v1
      - name: add cppfw deb repo
        uses: myci-actions/add-deb-repo@master
        with:
          repo: deb https://cppfw.jfrog.io/artifactory/${{ matrix.os }} ${{ matrix.codename }} main
          repo-name: cppfw
          key-server: https://cppfw.jfrog.io/artifactory/api/gpg/key/public
          keys: 0D76C39F3F352BAA9A42442AF57F79447F525F7D
      - name: install ci tools
        run: |
          # configure timezone to avoid 'tzdata' package to require user interaction during installation (needed for ubuntu:focal)
          TZ=Europe/Helsinki ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

          apt update
          apt install --assume-yes devscripts equivs myci
      - name: set PACKAGE_VERSION
        uses: myci-actions/export-env-var@master
        with: {name: PACKAGE_VERSION, value: $(myci-deb-version.sh debian/changelog)}
      - name: prepare debian package
        run: myci-deb-prepare.sh
      - name: install deps
        run: myci-deb-install-build-deps.sh
      - name: build
        run: dpkg-buildpackage --unsigned-source --unsigned-changes
      - name: deploy deb packages
        run: myci-deploy-debian-jfrog.sh --domain cppfw --repo ${{ matrix.os }} --distro ${{ matrix.codename }} --component main ../${PACKAGE_NAME}*_${PACKAGE_VERSION}_*.deb
        if: matrix.package_type == 'deb' && startsWith(github.ref, 'refs/tags/')
##### macosx #####
  macosx:
    runs-on: macos-latest
    steps:
    - name: git clone
      uses: actions/checkout@main
    - name: add cppfw tap
      run: |
        brew tap cppfw/tap
        brew update
    - name: install ci tools
      run: brew install myci
    - name: build
      run: make autojobs=true
    - name: test
      run: make test
    - name: deploy
      run: myci-deploy-homebrew.sh --tap cppfw/tap
      if: startsWith(github.ref, 'refs/tags/')
##### msys2 #####
  msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: make msys2 to provide the default shell
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: MSYS
        install: >-
          msys2-devel
          make
    - name: git clone
      uses: actions/checkout@main
    - name: add cppfw pacman msys repo
      uses: myci-actions/add-pacman-repo@master
      with: {name: cppfw_msys, url: 'https://dl.bintray.com/cppfw/msys2/msys', shell: 'msys2 {0}'}
    - name: install ci tools
      run: pacman -Sy --noconfirm myci
    - name: prepare pacman package
      run: myci-apply-version.sh -v $(myci-deb-version.sh debian/changelog) msys2/PKGBUILD.in
    - name: build
      run: |
        cd msys2
        makepkg --syncdeps --noconfirm --skipinteg
    - name: deploy
      run: myci-deploy-pacman-jfrog.sh --domain cppfw --repo msys2 --path msys --database cppfw_msys msys2/$PACKAGE_NAME-*-any.pkg.*
      if: startsWith(github.ref, 'refs/tags/')
